[tools]
acli = "latest"
ansible = { version = "14.2.0", pipx_args = "--include-deps", uvx = "false" }
atlas = "latest"
deck = "latest"
docker-cli = "latest"
go = "latest"
grpcurl = "latest"
gum = "latest"
helm = "latest"
java = "latest"
kubecolor = "latest"
kustomize = "latest"
maven = "3.9.12"
mysql = "latest"
node = "latest"
npm = "latest"
pipx = "latest"
pre-commit = "latest"
python = "latest"
redis = "latest"
terraform = "latest"
terragrunt = "latest"
"ubi:argoproj-labs/argocd-image-updater" = "latest"
