format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$kubernetes\
${custom.terraform}\
$cmd_duration\
$fill\
$time\
$line_break\
$python\
$character\
${custom.osc}\
"""

follow_symlinks = false
# add_newline = false

[directory]
style = "blue"

[time]
disabled = false
format = ' [$time]($style)'

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[git_branch]
format = "\\[[$branch]($style)"
style = "1"

[fill]
# symbol = '-'
# style = 'bold bright-green'
symbol = ' '
style = 'bold bright-green strikethrough'

[git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed)]($style)"
format = '$all_status$ahead_behind\]'
# ahead = '[⬆](bold purple)'
# behind = '[⬇](bold purple)'
# staged = '[✚](green)'
# deleted = '[✖](red)'
# renamed = '[➜](purple)'
# stashed = '[✭](cyan)'
ahead = ''
behind = ''
staged = ''
deleted = ''
renamed = ''
stashed = ''
# untracked = '[◼](white)'
# modified = '[✱](blue)'
# conflicted = '[═](yellow)'
# diverged = '⇕'
up_to_date = ''

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[cmd_duration]
format = " [$duration]($style) "
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[custom.terraform]
command = '''
env=$(jq -r '.backend.config' .terraform/terraform.tfstate | grep -oE 'dev|preview|qa|uat[0-9]?|sit[0-9]?|np|prod' | head -n 1)
case "$env" in
  dev) c="1;32" ;;
  sit*) c="1;36" ;;
  uat*) c="1;33" ;;
  prod) c="1;31" ;;
  *) c="1;35" ;;
esac
printf '[\033[1;35m󱁢 \033[0m\033[%sm%s\033[0m]' "$c" "$env"
'''
when = "test -f .terraform/terraform.tfstate"
unsafe_no_escape = true
format = '$output'

[kubernetes]
disabled = false
symbol = "󱃾 "
format = '\[[$symbol](bold blue)[$context( \($namespace\))]($style)\]'
style = "bold purple"

[[kubernetes.contexts]]
context_pattern = ".*prod.*"
style = "bold red"
#
[[kubernetes.contexts]]
context_pattern = ".*uat[0-9]?.*"
style = "bold yellow"
#
[[kubernetes.contexts]]
context_pattern = ".*sit[0-9]?.*"
style = "bold bright-cyan"
#
[[kubernetes.contexts]]
context_pattern = ".*dev.*"
style = "bold green"

[custom.osc]
command = '''printf "\033]133;A\007"'''
format = '[$symbol($output)]($style)'
when = true
